## AIM Module 6 Assignment Solutions

__1__. Write a Python/NumPy code block that finds the unique common items between these three arrays:

In [1]:
import numpy as np
a = np.array([1, 2, 3, 2, 3, 4, 3, 4, 5, 6])
b = np.array([7, 2, 10, 2, 7, 4, 9, 4, 9, 8])
c = np.array([12, 8, 3, 7, 4, 1, 2, 9, 3, 4])

# the question requires finding the intersection of the 3 arrays
np.intersect1d(np.intersect1d(a,b),c)

array([2, 4])

__2__. Create the following 3x6 array using knowledge you have of 
Python's/NumPy's sequencing functionality so that you do not need to 
explicitly key in every integer value.

In [2]:
np.arange(1,19).reshape(6,3).T

array([[ 1,  4,  7, 10, 13, 16],
       [ 2,  5,  8, 11, 14, 17],
       [ 3,  6,  9, 12, 15, 18]])

__3__. The process of transforming a multidimensional array into a unidimensional array is referred to as “flattening”. Transform the 3x6 array shown above in Problem 2 into a unidimensional array such that the sequence of values contained within the array is as follows: 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18

In [3]:
# reproduce the array from problem 2
p3 = np.arange(1,19).reshape(6,3).T
p3

array([[ 1,  4,  7, 10, 13, 16],
       [ 2,  5,  8, 11, 14, 17],
       [ 3,  6,  9, 12, 15, 18]])

In [4]:
# now flatten the array 
p3.flatten('F')

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18])

__4__. Transform the 2-D array shown in Problem 2 into a 3 dimensional array

In [5]:
# recreate the array from P2
p2 = np.arange(1,19).reshape(6,3).T
p2

array([[ 1,  4,  7, 10, 13, 16],
       [ 2,  5,  8, 11, 14, 17],
       [ 3,  6,  9, 12, 15, 18]])

In [6]:
# sample solution
p4 = np.reshape(p2.T, p2.T.shape + (1,))
print(p4)
print(p4.shape)

[[[ 1]
  [ 2]
  [ 3]]

 [[ 4]
  [ 5]
  [ 6]]

 [[ 7]
  [ 8]
  [ 9]]

 [[10]
  [11]
  [12]]

 [[13]
  [14]
  [15]]

 [[16]
  [17]
  [18]]]
(6, 3, 1)


In [7]:
# alternative solution:
p4 = np.reshape(p2.T,[6,3,1],'f')
p4

array([[[ 1],
        [ 2],
        [ 3]],

       [[ 4],
        [ 5],
        [ 6]],

       [[ 7],
        [ 8],
        [ 9]],

       [[10],
        [11],
        [12]],

       [[13],
        [14],
        [15]],

       [[16],
        [17],
        [18]]])

__5__. Transform the 3-D array you created in Problem 4 back to the 3x6 2-dimensional format shown in Problem 2.

In [8]:
p4.reshape(6,3).T

array([[ 1,  4,  7, 10, 13, 16],
       [ 2,  5,  8, 11, 14, 17],
       [ 3,  6,  9, 12, 15, 18]])

__6__. Write a Python/Numpy code block that removes from array a any items that are also present in either array b or array c.

In [2]:
a = np.array([12, 5, 7, 15, 3, 1, 8, 9, 2])
b = np.array([14, 2, 6, 3, 11, 19, 9, 12, 5])
c = np.array([1, 12, 4, 3, 13, 1, 9, 12, 5, 7])

# the setdiff1d() function removes items from array a that are also in array b
np.setdiff1d(np.setdiff1d(a,b),c)

array([ 8, 15])

__7__. NYC Water Usage Data

https://data.cityofnewyork.us/Environment/Water-Consumption-In-The-New-York-City/ia2d-e54m

In [9]:
import pandas
import numpy as np

# supress scientific notation
np.set_printoptions(suppress = True)

# read the data file from GitHub and convert to a NumPy ndarray object
nyc_water = pandas.read_csv('https://raw.githubusercontent.com/shenghanyueh/AIM-5001/main/Module6_Data.csv').to_numpy()

print(nyc_water)
print(type(nyc_water))

[[   1979.  7102100.     1512.      213. ]
 [   1980.  7071639.     1506.      213. ]
 [   1981.  7089241.     1309.      185. ]
 [   1982.  7109105.     1382.      194. ]
 [   1983.  7181224.     1424.      198. ]
 [   1984.  7234514.     1465.      203. ]
 [   1985.  7274054.     1326.      182. ]
 [   1986.  7319246.     1351.      185. ]
 [   1987.  7342476.     1447.      197. ]
 [   1988.  7353719.     1484.      202. ]
 [   1989.  7344175.     1402.      191. ]
 [   1990.  7335650.     1424.      194. ]
 [   1991.  7374501.     1469.      199. ]
 [   1992.  7428944.     1369.      184. ]
 [   1993.  7506166.     1368.5     182. ]
 [   1994.  7570458.     1357.7     179. ]
 [   1995.  7633040.     1325.7     174. ]
 [   1996.  7697812.     1297.9     169. ]
 [   1997.  7773443.     1205.5     155. ]
 [   1998.  7858259.     1219.5     155. ]
 [   1999.  7947660.     1237.2     156. ]
 [   2000.  8008278.     1240.4     155. ]
 [   2001.  8024963.5    1184.      148. ]
 [   2002. 

Which year had the minimum population amount?

In [10]:
# year = column 1; population = column 2
index = np.argmin(nyc_water[:, 1])
print('the year had the minimum population amount:')
nyc_water[index, 0]

the year had the minimum population amount:


1980.0

Add a new column to the numpy array containing the total annual water consumption for the city (in millions of gallons of water and assuming a 365 day calendar year).

In [11]:
# millions of gallons of water per day = column 3
nyc_water = np.concatenate((nyc_water, (nyc_water[:,2]*365).reshape(39,1)),axis=1)

In [13]:
nyc_water

array([[   1979. , 7102100. ,    1512. ,     213. ,  551880. ],
       [   1980. , 7071639. ,    1506. ,     213. ,  549690. ],
       [   1981. , 7089241. ,    1309. ,     185. ,  477785. ],
       [   1982. , 7109105. ,    1382. ,     194. ,  504430. ],
       [   1983. , 7181224. ,    1424. ,     198. ,  519760. ],
       [   1984. , 7234514. ,    1465. ,     203. ,  534725. ],
       [   1985. , 7274054. ,    1326. ,     182. ,  483990. ],
       [   1986. , 7319246. ,    1351. ,     185. ,  493115. ],
       [   1987. , 7342476. ,    1447. ,     197. ,  528155. ],
       [   1988. , 7353719. ,    1484. ,     202. ,  541660. ],
       [   1989. , 7344175. ,    1402. ,     191. ,  511730. ],
       [   1990. , 7335650. ,    1424. ,     194. ,  519760. ],
       [   1991. , 7374501. ,    1469. ,     199. ,  536185. ],
       [   1992. , 7428944. ,    1369. ,     184. ,  499685. ],
       [   1993. , 7506166. ,    1368.5,     182. ,  499502.5],
       [   1994. , 7570458. ,    1357.7,

What is the median and the variance of the NYC daily water consumption metric?

In [12]:
# daily water consumption = column 3
print('median of NYC daily water consumption:')
np.median(nyc_water[:,2])

median of NYC daily water consumption:


1237.2

In [13]:
print('variance of NYC daily water consumption:')
np.var(nyc_water[:,2])

variance of NYC daily water consumption:


29744.87353057199

What is the increase or decrease in total annual water consumption from year to year? 

In [16]:
# total annual water consumption is the last column in the array
# use np.diff() to calculate differences between consecutive
# array items
np.diff(nyc_water[:,-1])

array([ -2190. , -71905. ,  26645. ,  15330. ,  14965. , -50735. ,
         9125. ,  35040. ,  13505. , -29930. ,   8030. ,  16425. ,
       -36500. ,   -182.5,  -3942. , -11680. , -10147. , -33726. ,
         5110. ,   6460.5,   1168. , -20586. , -17666. , -15293.5,
         2117. ,  14052.5, -25185. ,  16425. ,  -5840. , -33032.5,
        11497.5,  -6570. ,  -4343.5,  -1095. ,  -3686.5,   4745. ,
        -2555. ,  -4307. ])